-- data.sql for Inventory Service
INSERT INTO inventory (product_id, quantity, last_updated) VALUES
(1, 100, CURRENT_TIMESTAMP),
(2, 80, CURRENT_TIMESTAMP),
(3, 150, CURRENT_TIMESTAMP),
(4, 70, CURRENT_TIMESTAMP),
(5, 50, CURRENT_TIMESTAMP),
(6, 200, CURRENT_TIMESTAMP),
(7, 90, CURRENT_TIMESTAMP),
(8, 110, CURRENT_TIMESTAMP),
(9, 40, CURRENT_TIMESTAMP),
(10, 120, CURRENT_TIMESTAMP);